import { useEffect, useState } from 'react';
import { Activity, Bell, ChevronDown, Menu, Moon, Search, Sun, Waves } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { lifecycleStages } from '../../services/projectData.js';

function CoreDashboard() {
  const { t } = useTranslation(); const content = t('content', { returnObjects: true }); const [darkTheme, setDarkTheme] = useState(() => localStorage.getItem('rc_dashboard_theme') === 'dark');
  useEffect(() => { document.documentElement.dataset.dashboardTheme = darkTheme ? 'dark' : 'light'; }, [darkTheme]); const toggleTheme = () => setDarkTheme((current) => { const next = !current; localStorage.setItem('rc_dashboard_theme', next ? 'dark' : 'light'); return next; });
  const widgets = [[t('private.place'), content.location], [t('private.work'), t('private.restoration')], [t('private.focus'), t('private.careMonitoring')], [t('private.participation'), t('private.community')]];
  return <section className={`core-dashboard${darkTheme ? ' core-dashboard--dark' : ''}`}><header className="core-dashboard__topbar"><button className="core-icon-button" type="button" aria-label={t('common.menu')}><Menu size={19} /></button><div className="core-search"><Search size={16} /><span>{t('common.search')}</span></div><div className="core-topbar__actions"><button className="core-icon-button" type="button" aria-label={t('common.notifications')}><Bell size={18} /></button><button className="core-icon-button" type="button" aria-label={t('common.activity')}><Activity size={18} /></button><button className="core-icon-button core-theme-toggle" type="button" aria-label={darkTheme ? t('common.lightTheme') : t('common.darkTheme')} aria-pressed={darkTheme} onClick={toggleTheme}>{darkTheme ? <Sun size={18} /> : <Moon size={18} />}</button></div></header><div className="core-dashboard__body"><nav className="core-breadcrumb" aria-label={t('common.breadcrumb')}><Link to="/dashboard">{t('common.home')}</Link><span>/</span><strong>{t('private.projectInfo')}</strong></nav><div className="core-dashboard__heading"><div><p className="eyebrow"><Waves size={14} /> {t('private.area')}</p><h1>{content.location}</h1></div><span className="core-demo-pill">{t('common.demo')}</span></div><div className="core-widgets">{widgets.map(([label, value]) => <article className="core-widget core-widget--coral" key={label}><div className="core-widget__top"><strong>•</strong></div><p>{label}</p><small>{value}</small></article>)}</div><section className="core-card core-traffic"><div className="core-card__header"><div><h2>{t('private.processTitle')}</h2><p>{t('private.processDescription')}</p></div></div><div className="core-lifecycle-list">{content.howWeWork.map((item, index) => <div className="core-context__item" key={item}><span>0{index + 1}</span><strong>{item}</strong></div>)}</div></section><div className="core-lower-grid"><section className="core-card core-activity"><div className="core-card__header"><div><h2>{t('private.lifecycle')}</h2><p>{t('private.lifecycleDescription')}</p></div></div><div className="core-table-wrap"><table><thead><tr><th>{t('private.stage')}</th><th>{t('private.description')}</th></tr></thead><tbody>{lifecycleStages.map((stage) => <tr key={stage.id}><td>{t(`lifecycle.${stage.id}.name`)}</td><td>{t(`lifecycle.${stage.id}.description`)}</td></tr>)}</tbody></table></div><Link className="core-card__link" to="/galeria">{t('private.exploreComplete')} <ChevronDown size={15} /></Link></section><section className="core-card core-context"><div className="core-card__header"><div><h2>{t('private.why')}</h2><p>{t('private.reefImportance')}</p></div></div><p>{content.whyRestore}</p><div className="core-context__item"><span>{t('private.location')}</span><strong>{content.location}</strong></div><div className="core-context__item"><span>{t('private.principle')}</span><strong>{t('private.collaborative')}</strong></div></section></div></div></section>;
}

export { CoreDashboard };
