import { useEffect, useState } from 'react';
import { Activity, Bell, ChevronDown, Menu, Moon, Search, Sun, Waves } from 'lucide-react';
import { Link } from 'react-router-dom';
import { lifecycleStages, projectInfo } from '../../services/projectData.js';

function CoreDashboard() {
  const [darkTheme, setDarkTheme] = useState(() => localStorage.getItem('rc_dashboard_theme') === 'dark');
  useEffect(() => { document.documentElement.dataset.dashboardTheme = darkTheme ? 'dark' : 'light'; }, [darkTheme]);
  const toggleTheme = () => setDarkTheme((current) => { const next = !current; localStorage.setItem('rc_dashboard_theme', next ? 'dark' : 'light'); return next; });
  return <section className={`core-dashboard${darkTheme ? ' core-dashboard--dark' : ''}`}><header className="core-dashboard__topbar"><button className="core-icon-button" type="button" aria-label="Abrir menú"><Menu size={19} /></button><div className="core-search"><Search size={16} /><span>Buscar</span></div><div className="core-topbar__actions"><button className="core-icon-button" type="button" aria-label="Notificaciones"><Bell size={18} /></button><button className="core-icon-button" type="button" aria-label="Actividad"><Activity size={18} /></button><button className="core-icon-button core-theme-toggle" type="button" aria-label={darkTheme ? 'Cambiar a tema claro' : 'Cambiar a tema oscuro'} aria-pressed={darkTheme} onClick={toggleTheme}>{darkTheme ? <Sun size={18} /> : <Moon size={18} />}</button></div></header><div className="core-dashboard__body"><nav className="core-breadcrumb" aria-label="Migas de pan"><Link to="/dashboard">Inicio</Link><span>/</span><strong>Información del proyecto</strong></nav><div className="core-dashboard__heading"><div><p className="eyebrow"><Waves size={14} /> Área de restauración</p><h1>{projectInfo.location}</h1></div><span className="core-demo-pill">Información del proyecto</span></div><div className="core-widgets">{[['Lugar', projectInfo.location], ['Trabajo', 'Restauración coralina'], ['Enfoque', 'Cuidado y monitoreo'], ['Participación', 'Comunidad e instituciones']].map(([label, value]) => <article className="core-widget core-widget--coral" key={label}><div className="core-widget__top"><strong>•</strong></div><p>{label}</p><small>{value}</small></article>)}</div><section className="core-card core-traffic"><div className="core-card__header"><div><h2>Proceso de restauración</h2><p>Etapas de trabajo descritas por el proyecto</p></div></div><div className="core-lifecycle-list">{projectInfo.howWeWork.map((item, index) => <div className="core-context__item" key={item}><span>0{index + 1}</span><strong>{item}</strong></div>)}</div></section><div className="core-lower-grid"><section className="core-card core-activity"><div className="core-card__header"><div><h2>Ciclo de vida</h2><p>Del gameto al coral adulto</p></div></div><div className="core-table-wrap"><table><thead><tr><th>Etapa</th><th>Descripción</th></tr></thead><tbody>{lifecycleStages.map((stage) => <tr key={stage.id}><td>{stage.name}</td><td>{stage.description}</td></tr>)}</tbody></table></div><Link className="core-card__link" to="/galeria">Explorar el ciclo completo <ChevronDown size={15} /></Link></section><section className="core-card core-context"><div className="core-card__header"><div><h2>Por qué restaurar</h2><p>Importancia del arrecife</p></div></div><p>{projectInfo.whyRestore}</p><div className="core-context__item"><span>Ubicación</span><strong>{projectInfo.location}</strong></div><div className="core-context__item"><span>Principio</span><strong>Trabajo colaborativo</strong></div></section></div></div></section>;
}

export { CoreDashboard };
