import { useState } from 'react';
import { Activity, Bell, Menu, Moon, Search, Sun } from 'lucide-react';
import { Link } from 'react-router-dom';

export function ObservationsPage() {
  const [saved, setSaved] = useState(false);
  const [darkTheme, setDarkTheme] = useState(() => localStorage.getItem('rc_dashboard_theme') === 'dark');
  const toggleTheme = () => setDarkTheme((current) => { const next = !current; localStorage.setItem('rc_dashboard_theme', next ? 'dark' : 'light'); document.documentElement.dataset.dashboardTheme = next ? 'dark' : 'light'; return next; });
  return <section className="observation-page"><header className="private-section-topbar"><button className="private-section-menu" type="button" aria-label="Menú"><Menu size={19} /></button><div className="private-section-search"><Search size={16} /><span>Buscar</span><kbd>Ctrl</kbd><kbd>/</kbd></div><div className="private-section-actions"><Bell size={18} /><Activity size={18} /><button className="private-section-theme-toggle" type="button" aria-label={darkTheme ? 'Cambiar a tema claro' : 'Cambiar a tema oscuro'} aria-pressed={darkTheme} onClick={toggleTheme}>{darkTheme ? <Sun size={18} /> : <Moon size={18} />}</button><span className="private-section-avatar">RC</span></div></header><nav className="private-section-breadcrumb" aria-label="Migas de pan"><Link to="/dashboard">Inicio</Link><span>/</span><strong>Registro de trabajo</strong></nav><div className="observation-page__content"><p className="eyebrow">Seguimiento de campo</p><h1>Registrar actividad</h1><p>Completa este formulario únicamente con información confirmada por el equipo del proyecto.</p><form className="panel form" onSubmit={(event) => { event.preventDefault(); setSaved(true); }}><label>Fragmento, coral o estructura<input required /></label><label>Fecha<input required type="date" /></label><label>Actividad<select><option>Selección y recolección</option><option>Colocación en guardería marina</option><option>Limpieza y mantenimiento</option><option>Monitoreo</option></select></label><label>Responsable<input required /></label><label className="full">Notas y evidencia disponible<textarea /></label><button className="button full">Guardar registro</button>{saved && <p className="success full">Registro guardado localmente. Su validación queda pendiente del equipo responsable.</p>}</form></div></section>;
}
