import { useState } from 'react';
import { Activity, Bell, Menu, Moon, Search, Sun } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';

export function ObservationsPage() {
  const { t } = useTranslation(); const [saved, setSaved] = useState(false); const [darkTheme, setDarkTheme] = useState(() => localStorage.getItem('rc_dashboard_theme') === 'dark'); const toggleTheme = () => setDarkTheme((current) => { const next = !current; localStorage.setItem('rc_dashboard_theme', next ? 'dark' : 'light'); document.documentElement.dataset.dashboardTheme = next ? 'dark' : 'light'; return next; });
  return <section className="observation-page"><header className="private-section-topbar"><button className="private-section-menu" type="button" aria-label={t('common.menu')}><Menu size={19} /></button><div className="private-section-search"><Search size={16} /><span>{t('common.search')}</span><kbd>Ctrl</kbd><kbd>/</kbd></div><div className="private-section-actions"><Bell size={18} aria-label={t('common.notifications')} /><Activity size={18} aria-label={t('common.activity')} /><button className="private-section-theme-toggle" type="button" aria-label={darkTheme ? t('common.lightTheme') : t('common.darkTheme')} aria-pressed={darkTheme} onClick={toggleTheme}>{darkTheme ? <Sun size={18} /> : <Moon size={18} />}</button><span className="private-section-avatar">RC</span></div></header><nav className="private-section-breadcrumb" aria-label={t('common.breadcrumb')}><Link to="/dashboard">{t('common.home')}</Link><span>/</span><strong>{t('private.recordWork')}</strong></nav><div className="observation-page__content"><p className="eyebrow">{t('common.fieldTracking')}</p><h1>{t('private.registerActivity')}</h1><p>{t('private.formIntro')}</p><form className="panel form" onSubmit={(event) => { event.preventDefault(); setSaved(true); }}><label>{t('private.fragment')}<input required /></label><label>{t('private.date')}<input required type="date" /></label><label>{t('private.activity')}<select><option>{t('private.selectCollection')}</option><option>{t('private.nursery')}</option><option>{t('private.maintenance')}</option><option>{t('private.monitoring')}</option></select></label><label>{t('private.responsible')}<input required /></label><label className="full">{t('private.notes')}<textarea /></label><button className="button full">{t('common.save')}</button>{saved && <p className="success full">{t('private.saved')}</p>}</form></div></section>;
}
