import { useState } from 'react';
import { ArrowLeft, ArrowRight, Camera, MapPin, Waves } from 'lucide-react';
import { Link } from 'react-router-dom';
import { lifecycleAssets } from '../../services/lifecycleAssets.js';
import { lifecycleStages, projectInfo } from '../../services/projectData.js';
import '../../interactive-public-pages.css';

export function InteractiveMapPage() {
  return <main className="public-page interactive-page"><section className="interactive-hero"><div><p className="vh-kicker"><Waves size={15} /> ¿Dónde trabajamos?</p><h1>Isla Tortuga<br /><em>Golfo de Nicoya.</em></h1><p>{projectInfo.locationDescription}</p></div></section><section className="public-content public-content--map interactive-map-layout"><div className="public-map interactive-map" role="img" aria-label="Área de trabajo indicada de forma general, sin coordenadas sensibles"><div className="public-map__label"><MapPin size={15} /> {projectInfo.location}</div><div className="public-map__note">Área de trabajo<br />Sin coordenadas sensibles</div></div><div className="public-list"><div className="public-list__heading"><div><p className="vh-kicker">Restauración coralina</p><h2>¿Qué se hace?</h2></div><span>Proceso</span></div>{projectInfo.howWeWork.map((item, index) => <article className="public-record" key={item}><span className="public-record__code">0{index + 1}</span><span className="public-record__details"><b>{item}</b><small>Trabajo de restauración</small></span><ArrowRight size={16} /></article>)}<Link className="vh-text-link" to="/proyecto">Ver el proceso completo <ArrowRight size={16} /></Link></div></section></main>;
}

export function InteractiveGallery() {
  const [activeImage, setActiveImage] = useState(0);
  const stage = lifecycleStages[activeImage];
  const stageAsset = lifecycleAssets[stage.id];
  const changeStage = (nextIndex) => setActiveImage((nextIndex + lifecycleStages.length) % lifecycleStages.length);
  return <main className="public-page interactive-page"><section className="interactive-hero interactive-hero--gallery"><div><p className="vh-kicker"><Camera size={15} /> Ciclo de vida del coral</p><h1>Del gameto<br /><em>al coral adulto.</em></h1><p>El coral atraviesa distintas etapas antes de formar una colonia adulta. Explora cada modelo para ver su nombre e información.</p></div></section><section className="interactive-gallery" aria-label="Carrusel del ciclo de vida del coral"><div className="interactive-gallery__hero"><div className="lifecycle-stage-visual" aria-label={`Imagen interactiva de ${stage.name}`}><button className={`lifecycle-model lifecycle-model--${stage.id}`} type="button" aria-label={`Destacar ${stage.name}`}><img className="lifecycle-model__image" src={stageAsset} alt="" aria-hidden="true" decoding="async" loading="lazy" width="1254" height="1254" /><span className="lifecycle-model__halo" aria-hidden="true" /><span className="lifecycle-stage-tooltip"><strong>{stage.name}</strong><small>{stage.description}</small></span></button><div className="lifecycle-stage-visual__waterline" aria-hidden="true" /></div><div className="interactive-gallery__copy"><p className="vh-kicker"><Camera size={14} /> Etapa {activeImage + 1} de {lifecycleStages.length}</p><h2 id="lifecycle-stage-title">{stage.name}</h2><p>{stage.description}</p><span className="lifecycle-demo-note">Contenido informativo de referencia · no es registro de campo</span><div className="lifecycle-controls"><button type="button" aria-label="Etapa anterior" onClick={() => changeStage(activeImage - 1)}><ArrowLeft size={16} /></button><button type="button" aria-label="Etapa siguiente" onClick={() => changeStage(activeImage + 1)}><ArrowRight size={16} /></button></div></div></div><div className="interactive-gallery__rail" role="tablist" aria-label="Seleccionar etapa del ciclo de vida">{lifecycleStages.map((item, index) => <button className={activeImage === index ? 'is-active' : ''} key={item.id} type="button" role="tab" aria-selected={activeImage === index} aria-controls="lifecycle-stage-title" onClick={() => setActiveImage(index)}><span className={`lifecycle-thumb lifecycle-thumb--${item.id}`} aria-hidden="true"><img src={lifecycleAssets[item.id]} alt="" decoding="async" loading="lazy" width="1254" height="1254" /></span><span>{String(index + 1).padStart(2, '0')}<small>{item.name}</small></span></button>)}</div></section></main>;
}
