import { useState } from 'react';
import { ArrowLeft, ArrowRight, Camera, Waves } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { RestorationMap } from '../../components/map/RestorationMap.jsx';
import { WeatherCard } from '../../components/weather/WeatherCard.jsx';
import { lifecycleAssets } from '../../services/lifecycleAssets.js';
import { lifecycleStages, projectInfo } from '../../services/projectData.js';
import '../../interactive-public-pages.css';

export function InteractiveMapPage() {
  const { t } = useTranslation(); const content = projectInfo;
  return <main className="public-page interactive-page"><section className="interactive-hero"><div><p className="vh-kicker"><Waves size={15} /> {t('map.where')}</p><h1>{t('map.title')}<br /><em>{t('map.titleEmphasis')}</em></h1><p>{content.locationDescription}</p></div></section><section className="weather-section"><WeatherCard /></section><section className="public-content public-content--map interactive-map-layout"><RestorationMap /><div className="public-list"><div className="public-list__heading"><div><p className="vh-kicker">{t('map.restoration')}</p><h2>{t('map.what')}</h2></div><span>{t('map.process')}</span></div>{content.howWeWork.map((item, index) => <article className="public-record" key={item}><span className="public-record__code">0{index + 1}</span><span className="public-record__details"><b>{item}</b><small>{t('map.work')}</small></span></article>)}<Link className="vh-text-link" to="/proyecto">{t('map.complete')} <ArrowRight size={16} /></Link></div></section></main>;
}

export function InteractiveGallery() {
  const { t } = useTranslation(); const [activeImage, setActiveImage] = useState(0); const stage = lifecycleStages[activeImage]; const name = t(`lifecycle.${stage.id}.name`); const description = t(`lifecycle.${stage.id}.description`); const changeStage = (nextIndex) => setActiveImage((nextIndex + lifecycleStages.length) % lifecycleStages.length);
  return <main className="public-page interactive-page"><section className="interactive-hero interactive-hero--gallery"><div><p className="vh-kicker"><Camera size={15} /> {t('gallery.kicker')}</p><h1>{t('gallery.title')}<br /><em>{t('gallery.titleEmphasis')}</em></h1><p>{t('gallery.intro')}</p></div></section><section className="interactive-gallery" aria-label={t('gallery.carousel')}><div className="interactive-gallery__hero"><div className="lifecycle-stage-visual" aria-label={t('gallery.image', { name })}><button className={`lifecycle-model lifecycle-model--${stage.id}`} type="button" aria-label={t('home.highlight', { name })}><img className="lifecycle-model__image" src={lifecycleAssets[stage.id]} alt="" aria-hidden="true" decoding="async" loading="lazy" width="1254" height="1254" /><span className="lifecycle-model__halo" aria-hidden="true" /><span className="lifecycle-stage-tooltip"><strong>{name}</strong><small>{description}</small></span></button><div className="lifecycle-stage-visual__waterline" aria-hidden="true" /></div><div className="interactive-gallery__copy"><p className="vh-kicker"><Camera size={14} /> {t('gallery.stage', { current: activeImage + 1, total: lifecycleStages.length })}</p><h2 id="lifecycle-stage-title">{name}</h2><p>{description}</p><span className="lifecycle-demo-note">{t('gallery.reference')}</span><div className="lifecycle-controls"><button type="button" aria-label={t('common.previous')} onClick={() => changeStage(activeImage - 1)}><ArrowLeft size={16} /></button><button type="button" aria-label={t('common.next')} onClick={() => changeStage(activeImage + 1)}><ArrowRight size={16} /></button></div></div></div><div className="interactive-gallery__rail" role="tablist" aria-label={t('home.selectStage')}>{lifecycleStages.map((item, index) => <button className={activeImage === index ? 'is-active' : ''} key={item.id} type="button" role="tab" aria-selected={activeImage === index} aria-controls="lifecycle-stage-title" onClick={() => setActiveImage(index)}><span className={`lifecycle-thumb lifecycle-thumb--${item.id}`} aria-hidden="true"><img src={lifecycleAssets[item.id]} alt="" decoding="async" loading="lazy" width="1254" height="1254" /></span><span>{String(index + 1).padStart(2, '0')}<small>{t(`lifecycle.${item.id}.name`)}</small></span></button>)}</div></section></main>;
}
