import { useEffect, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Fish, Waves } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import '../../i18n/index.js';
import descentBackground from '../../assets/isla-tortuga-long-scroll.png';
import { lifecycleStages } from '../../services/projectData.js';
import { lifecycleAssets } from '../../services/lifecycleAssets.js';
import '../../public-home.css';
import '../../interactive-public-pages.css';

export function PublicHome() {
  const { t } = useTranslation();
  const [activeId, setActiveId] = useState('location');
  const [activeStageId, setActiveStageId] = useState(lifecycleStages[0].id);
  const [scrollProgress, setScrollProgress] = useState(0);
  const content = t('content', { returnObjects: true });
  const stories = [{ id: 'location', label: t('home.tabLocation'), heading: content.location, description: content.locationDescription, marker: '01' }, { id: 'process', label: t('home.tabProcess'), heading: t('home.processHeading'), description: content.howWeWork.join(' '), marker: '02' }, { id: 'collaboration', label: t('home.tabPeople'), heading: t('project.collaborationTitle'), description: content.collaboration, marker: '03' }];
  const activeStory = stories.find((story) => story.id === activeId) ?? stories[0];
  const activeStage = lifecycleStages.find((stage) => stage.id === activeStageId) ?? lifecycleStages[0];
  const stageName = t(`lifecycle.${activeStage.id}.name`); const stageDescription = t(`lifecycle.${activeStage.id}.description`);
  const immersionProgress = Math.min(scrollProgress * 3.2, 1); const activeStageIndex = lifecycleStages.indexOf(activeStage); const changeStage = (nextIndex) => setActiveStageId(lifecycleStages[(nextIndex + lifecycleStages.length) % lifecycleStages.length].id);
  useEffect(() => { const updateDepth = () => setScrollProgress(Math.min(window.scrollY / Math.max(document.documentElement.scrollHeight - window.innerHeight, 1), 1)); updateDepth(); window.addEventListener('scroll', updateDepth, { passive: true }); return () => window.removeEventListener('scroll', updateDepth); }, []);
  useEffect(() => { const items = [...document.querySelectorAll('.vh-reveal')]; const reduce = window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches ?? false; if (reduce || !('IntersectionObserver' in window)) { items.forEach((item) => item.classList.add('is-visible')); return undefined; } const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold: 0.16 }); items.forEach((item) => observer.observe(item)); return () => observer.disconnect(); }, []);
  return <main className="velorah-home" style={{ '--vh-scroll': scrollProgress, '--vh-depth': immersionProgress, '--vh-underwater-image': `url(${descentBackground})` }}><div className="vh-water-atmosphere" aria-hidden="true" /><div className="vh-depth-meter" aria-hidden="true"><span className="vh-depth-meter__line"><i style={{ transform: `scaleY(${Math.max(scrollProgress, 0.08)})` }} /></span><span>{t('home.surface')}</span><span>{t('home.underwater')}</span></div>
    <section className="vh-hero" aria-labelledby="home-title"><div className="vh-hero__image" aria-hidden="true" /><div className="vh-hero__content"><p className="vh-kicker"><Waves size={15} /> {content.location}</p><h1 id="home-title">{t('home.title')}<br /><em>{t('home.titleEmphasis')}</em></h1><p className="vh-hero__intro">{t('home.intro')}</p><div className="vh-actions"><Link className="vh-button vh-button--light" to="/proyecto">{t('home.learnProject')} <ArrowRight size={16} /></Link><Link className="vh-button vh-button--glass" to="/galeria">{t('home.viewLifecycle')}</Link></div></div><button className="vh-scroll" type="button" onClick={() => document.getElementById('seguimiento')?.scrollIntoView?.({ behavior: 'smooth', block: 'start' })}><span>{t('home.explore')}</span><ArrowDown size={15} /></button></section>
    <section className="vh-facts vh-reveal" aria-label={t('home.factsLabel')}><div className="vh-facts__intro"><h2>{t('home.factsTitle')} <em>{t('home.factsEmphasis')}</em></h2><p>{content.whyRestore}</p></div><div className="vh-facts__grid"><article className="vh-fact-card"><strong>01</strong><h3>{t('home.fact1Title')}</h3><p>{t('home.fact1')}</p></article><article className="vh-fact-card"><strong>02</strong><h3>{t('home.fact2Title')}</h3><p>{t('home.fact2')}</p></article><article className="vh-fact-card"><strong>03</strong><h3>{t('home.fact3Title')}</h3><p>{t('home.fact3')}</p></article></div></section>
    <section className="vh-statement vh-reveal" id="seguimiento"><h2>{t('home.statementTitle')}<br /><em>{t('home.statementEmphasis')}</em></h2><p>{content.collaboration}</p></section>
    <section className="vh-feature vh-reveal" aria-labelledby="feature-title"><div className="vh-feature__copy"><h2 id="feature-title">{t('home.featureTitle')}<br /><em>{t('home.featureEmphasis')}</em></h2><div className="vh-tabs" role="tablist" aria-label={t('home.tabsLabel')}>{stories.map((story) => <button key={story.id} type="button" role="tab" id={`tab-${story.id}`} aria-selected={story.id === activeId} aria-controls="story-panel" onClick={() => setActiveId(story.id)}>{story.label}</button>)}</div><div className="vh-story" id="story-panel" role="tabpanel" aria-labelledby={`tab-${activeStory.id}`}><span className="vh-story__marker">{activeStory.marker}</span><h3>{activeStory.heading}</h3><p>{activeStory.description}</p></div><div className="vh-feature__links"><Link className="vh-text-link" to="/proyecto">{t('home.workLink')} <ArrowRight size={16} /></Link><a className="vh-text-link vh-text-link--corals" href="#corales">{t('home.stagesLink')} <ArrowDown size={16} /></a></div></div><div className="vh-feature__visual" role="img" aria-label={t('home.illustrativeReef')}><div className="vh-visual__wash" /><Fish className="vh-visual__fish" size={34} aria-hidden="true" /></div></section>
    <section className="vh-reef vh-reveal" id="corales" aria-labelledby="reef-title"><div className="vh-reef__intro"><h2 id="reef-title">{t('home.reefTitle')}<br /><em>{t('home.reefEmphasis')}</em></h2><p>{t('home.reefIntro')}</p></div><div className="vh-reef__scene vh-lifecycle-scene" role="group" aria-label={t('home.carouselLabel')}><div className="lifecycle-stage-visual lifecycle-stage-visual--home" aria-label={t('home.model', { name: stageName })}><button className={`lifecycle-model lifecycle-model--${activeStage.id}`} type="button" aria-label={t('home.highlight', { name: stageName })}><img className="lifecycle-model__image" src={lifecycleAssets[activeStage.id]} alt="" aria-hidden="true" decoding="async" loading="lazy" width="1254" height="1254" /><span className="lifecycle-model__halo" aria-hidden="true" /><span className="lifecycle-stage-tooltip"><strong>{stageName}</strong><small>{stageDescription}</small></span></button><div className="lifecycle-stage-visual__waterline" aria-hidden="true" /></div><div className="vh-coral-card" aria-live="polite"><strong>{stageName}</strong><p>{stageDescription}</p></div><div className="vh-lifecycle-controls"><button type="button" aria-label={t('common.previous')} onClick={() => changeStage(activeStageIndex - 1)}><ArrowLeft size={15} /></button><button type="button" aria-label={t('common.next')} onClick={() => changeStage(activeStageIndex + 1)}><ArrowRight size={15} /></button></div><div className="vh-lifecycle-rail" role="tablist" aria-label={t('home.selectStage')}>{lifecycleStages.map((item, index) => <button className={activeStage.id === item.id ? 'is-active' : ''} key={item.id} type="button" role="tab" aria-selected={activeStage.id === item.id} onClick={() => setActiveStageId(item.id)}><span>{String(index + 1).padStart(2, '0')}</span><small>{t(`lifecycle.${item.id}.name`)}</small></button>)}</div></div></section>
    <section className="vh-cta vh-reveal"><h2>{t('home.ctaTitle')}<br /><em>{t('home.ctaEmphasis')}</em></h2><p>{t('home.ctaText')}</p><Link className="vh-button vh-button--light" to="/proyecto">{t('home.restorationLink')} <ArrowRight size={16} /></Link></section><button className={`vh-back-top${scrollProgress > 0.22 ? ' is-visible' : ''}`} type="button" aria-label={t('common.backToTop')} onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}><ArrowUp size={16} /></button>
  </main>;
}
