import React, { createContext, useContext, useState } from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Navigate, Outlet, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { Activity, ArrowRight, Bell, CalendarDays, Camera, Fish, HeartPulse, LogOut, Map, MapPin, Menu, Moon, Search, ShieldCheck, Sun, Waves } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { PublicHome } from './PublicHome.jsx';
import { InteractiveGallery, InteractiveMapPage } from './InteractivePublicPages.jsx';
import './public-pages.css';
import './styles.css';
import { CoreDashboard } from './CoreDashboard.jsx';

const Auth = createContext(null);
function AuthProvider({ children }) { const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('rc_user') || 'null')); const login = (email, password) => { if (email === 'admin@restauracion.local' && password === 'admin123') { const u = { name: 'Bernny Dumani Vásquez', role: 'admin' }; localStorage.setItem('rc_user', JSON.stringify(u)); setUser(u); return true; } return false; }; const logout = () => { localStorage.removeItem('rc_user'); setUser(null); }; return <Auth.Provider value={{ user, login, logout }}>{children}</Auth.Provider>; }
const useAuth = () => useContext(Auth);
const corals = [{ id: 'c1', code: 'RC-001', species: 'Porites sp.', status: 'Vivo', zone: 'Zona Carolina Norte' }, { id: 'c2', code: 'RC-002', species: 'Pocillopora sp.', status: 'Enfermo', zone: 'Sector Tortuga Sur' }, { id: 'c3', code: 'RC-003', species: 'Por confirmar', status: 'Pendiente de siembra', zone: 'Sector Tortuga Sur' }];
const evolution = [{ month: 'Jun', vivos: 8, enfermos: 2 }, { month: 'Jul', vivos: 12, enfermos: 3 }, { month: 'Ago', vivos: 17, enfermos: 2 }, { month: 'Sep', vivos: 21, enfermos: 3 }];

function PublicLayout() { return <div className="public-site"><header className="public-header"><Link className="brand" to="/"><Waves size={20}/> <span>Restauración Carolina</span></Link><nav className="public-nav" aria-label="Navegación principal"><NavLink to="/proyecto">Proyecto</NavLink><NavLink to="/mapa">Mapa</NavLink><NavLink to="/galeria">Galería</NavLink><NavLink to="/noticias">Noticias</NavLink><NavLink className="public-nav__access" to="/login">Acceso <ArrowRight size={14}/></NavLink></nav></header><Outlet/><footer className="public-footer"><Link className="brand" to="/"><Waves size={18}/> Restauración Carolina</Link><span>Prototipo académico · Datos demostrativos · Isla Tortuga</span></footer></div>; }
function PrivateLayout() { const { user, logout } = useAuth(); const [collapsed, setCollapsed] = useState(false); return <div className={`private${collapsed ? ' private--collapsed' : ''}`}><aside><Link className="brand" to="/dashboard" aria-label="Mostrar u ocultar menú Carolina" aria-expanded={!collapsed} onClick={(event) => { event.preventDefault(); setCollapsed((current) => !current); }}><Waves size={20}/> <span>Carolina</span></Link><p className="eyebrow">Sesión activa</p><strong>{user?.name}</strong><small>{user?.role}</small><Link to="/dashboard"><Activity size={16}/> <span>Dashboard</span></Link><Link to="/mapa"><Map size={16}/> <span>Mapa</span></Link><Link to="/observaciones"><Camera size={16}/> <span>Observaciones</span></Link><button className="button ghost" onClick={logout}><LogOut size={15}/> Salir</button></aside><main className="private-main"><Outlet/></main></div>; }
function PrivateRoute() { return useAuth().user ? <Outlet/> : <Navigate to="/login" replace/>; }
function Home() { return <PublicHome/>; }
function PageIntro({ eyebrow, title, children, number }) { return <section className="public-page-hero"><div className="public-page-hero__texture"/><div className="public-page-hero__content"><p className="vh-kicker"><Waves size={15}/>{eyebrow}</p><h1>{title}</h1><p>{children}</p></div><span className="public-page-hero__number">{number}</span></section>; }
function Project() { return <main className="public-page"><PageIntro eyebrow="El proyecto · Restauración Carolina" title={<>Observar para<br/><em>comprender mejor.</em></>} number="02 / 06">Un prototipo para reunir información trazable sobre zonas, estructuras, corales y visitas en Isla Tortuga y el Golfo de Nicoya.</PageIntro><section className="public-content public-content--split"><div className="public-content__heading"><p className="vh-kicker">Propósito</p><h2>Una mirada ordenada<br/><em>a cada visita.</em></h2></div><div className="public-content__body"><p>El sistema organiza registros de seguimiento para comparar cambios entre visitas y mantener visible el contexto de cada dato.</p><p>La información real de campo, los protocolos, responsables, permisos y coordenadas deben ser confirmados por el equipo del proyecto.</p></div></section><section className="public-principles"><article><span>01</span><h2>Registrar</h2><p>Relacionar observaciones con fecha, responsable, estado y evidencia disponible.</p></article><article><span>02</span><h2>Revisar</h2><p>Distinguir datos demostrativos, pendientes de validación y registros verificados.</p></article><article><span>03</span><h2>Respetar límites</h2><p>No diagnosticar, recomendar intervenciones ni sustituir revisión especializada.</p></article></section></main>; }
function MapPage() { return <main className="public-page"><PageIntro eyebrow="Exploración · Vista demostrativa" title={<>Zonas de<br/><em>seguimiento.</em></>} number="03 / 06">Explora registros de muestra. El mapa es ilustrativo y no publica coordenadas sensibles.</PageIntro><section className="public-content public-content--map"><div className="public-map" role="img" aria-label="Representación ilustrativa de zonas, sin coordenadas geográficas"><div className="public-map__label"><MapPin size={15}/> Golfo de Nicoya · ilustración</div><span className="public-map__reef public-map__reef--one"/><span className="public-map__reef public-map__reef--two"/><span className="public-map__reef public-map__reef--three"/><div className="public-map__note">Mapa demostrativo<br/>Ubicaciones no geográficas</div></div><div className="public-list"><div className="public-list__heading"><div><p className="vh-kicker">Registros asociados</p><h2>Corales de muestra</h2></div><span>{corals.length} registros</span></div>{corals.map(c => <Link className="public-record" key={c.id} to={`/corales/${c.id}`}><span className="public-record__code">{c.code}</span><span className="public-record__details"><b>{c.species}</b><small>{c.zone}</small></span><em>{c.status}</em><ArrowRight size={16}/></Link>)}</div></section></main>; }
function Login() { const { user, login } = useAuth(); const nav = useNavigate(); const [email, setEmail] = useState('admin@restauracion.local'); const [password, setPassword] = useState('admin123'); const [error, setError] = useState(''); if (user) return <Navigate to="/dashboard"/>; return <main className="public-page public-page--login"><PageIntro eyebrow="Acceso · Área de seguimiento" title={<>Un espacio para<br/><em>los registros.</em></>} number="06 / 06">Ingresa al área privada del prototipo para consultar el panel y registrar observaciones demostrativas.</PageIntro><section className="public-login-wrap"><div className="public-login-context"><p className="vh-kicker">Sesión de demostración</p><h2>Seguimiento con<br/><em>contexto.</em></h2><p>El acceso de prueba permite recorrer las funciones disponibles. Los registros generados aquí son demostrativos.</p><div className="public-login-demo"><span>Correo demo</span><b>admin@restauracion.local</b><span>Contraseña demo</span><b>admin123</b></div></div><form className="public-login-form" onSubmit={e => { e.preventDefault(); login(email, password) ? nav('/dashboard') : setError('Credenciales incorrectas'); }}><p className="vh-kicker">Acceso privado</p><h2>Iniciar sesión</h2><label>Correo electrónico<input type="email" autoComplete="username" value={email} onChange={e => setEmail(e.target.value)}/></label><label>Contraseña<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)}/></label>{error && <p className="public-login-error" role="alert">{error}</p>}<button className="vh-button vh-button--light" type="submit">Entrar al seguimiento <ArrowRight size={16}/></button></form></section></main>; }
function Dashboard() { const live = corals.filter(c => c.status === 'Vivo').length; return <section><p className="eyebrow">Panel privado</p><h1>Estado de restauración</h1><div className="metrics"><div><HeartPulse/><b>{live}</b><span>Corales vivos</span></div><div><Activity/><b>1</b><span>Enfermos</span></div><div><Waves/><b>1</b><span>Pendientes</span></div></div><div className="panel chart"><h2>Evolución demostrativa</h2><p>Datos ilustrativos, no resultados científicos.</p><ResponsiveContainer width="100%" height={300}><LineChart data={evolution}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Line dataKey="vivos" stroke="#087f8c" strokeWidth={3}/><Line dataKey="enfermos" stroke="#d97745" strokeWidth={3}/></LineChart></ResponsiveContainer></div></section>; }
function Observations() { const [saved, setSaved] = useState(false); const [darkTheme, setDarkTheme] = useState(() => localStorage.getItem('rc_dashboard_theme') === 'dark'); const toggleTheme = () => setDarkTheme((current) => { const next = !current; localStorage.setItem('rc_dashboard_theme', next ? 'dark' : 'light'); document.documentElement.dataset.dashboardTheme = next ? 'dark' : 'light'; return next; }); return <section className="observation-page"><header className="private-section-topbar"><button className="private-section-menu" type="button" aria-label="Menú"><Menu size={19}/></button><div className="private-section-search"><Search size={16}/><span>Buscar</span><kbd>Ctrl</kbd><kbd>/</kbd></div><div className="private-section-actions"><Bell size={18}/><Activity size={18}/><button className="private-section-theme-toggle" type="button" aria-label={darkTheme ? 'Cambiar a tema claro' : 'Cambiar a tema oscuro'} aria-pressed={darkTheme} onClick={toggleTheme}>{darkTheme ? <Sun size={18}/> : <Moon size={18}/>}</button><span className="private-section-avatar">BD</span></div></header><nav className="private-section-breadcrumb" aria-label="Migas de pan"><Link to="/dashboard">Inicio</Link><span>/</span><strong>Observaciones</strong></nav><div className="observation-page__content"><p className="eyebrow">Seguimiento</p><h1>Nueva observación</h1><form className="panel form" onSubmit={e => { e.preventDefault(); setSaved(true); }}><label>Coral<input required placeholder="RC-001"/></label><label>Fecha<input required type="date"/></label><label>Estado<select><option>Vivo</option><option>Enfermo</option><option>En observación</option><option>Pendiente de siembra</option></select></label><label>Observador<input required placeholder="Nombre"/></label><label className="full">Notas<textarea/></label><button className="button full">Guardar observación demo</button>{saved && <p className="success full">Registro guardado en modo demostrativo.</p>}</form></div></section>; }
function Coral() { const coral = corals.find(c => c.id === useParams().id); return <main className="public-page"><PageIntro eyebrow="Detalle · Registro demostrativo" title={<>{coral?.code || 'Coral no encontrado'}</>} number="Registro">Consulta la información de muestra asociada a este registro.</PageIntro>{coral && <section className="public-content public-content--split"><div><p className="vh-kicker">Estado actual</p><h2>{coral.species}</h2><p>{coral.zone} · <strong>{coral.status}</strong></p></div><div className="public-content__body"><p>Los datos de este registro son demostrativos. El historial se ampliará con observaciones, evidencia y validaciones.</p><Link className="vh-text-link" to="/mapa">Volver al mapa <ArrowRight size={16}/></Link></div></section>}</main>; }
function Gallery() { const images = [{ src: 'photo-1546026423-cc4642628d2b', alt: 'Arrecife coralino bajo el agua' }, { src: 'photo-1544551763-46a013bb70d5', alt: 'Buceo recreativo en aguas tropicales' }, { src: 'photo-1518467166778-b88f373ffec7', alt: 'Vida marina en un arrecife' }]; return <main className="public-page"><PageIntro eyebrow="Galería · Imágenes ilustrativas" title={<>Una ventana<br/><em>bajo el agua.</em></>} number="04 / 06">Imágenes de referencia para la experiencia visual. No representan observaciones de campo del proyecto.</PageIntro><section className="public-gallery" aria-label="Galería ilustrativa">{images.map((image, index) => <figure key={image.src}><img src={`https://images.unsplash.com/${image.src}?auto=format&fit=crop&w=1000&q=80`} alt={image.alt}/><figcaption><Camera size={14}/> Referencia ilustrativa · 0{index + 1}</figcaption></figure>)}</section></main>; }
function News() { return <main className="public-page"><PageIntro eyebrow="Noticias · Agenda demostrativa" title={<>Lo que ocurre<br/><em>en el proyecto.</em></>} number="05 / 06">Comunicaciones de ejemplo y actividades planificadas en los datos demostrativos.</PageIntro><section className="public-news"><article className="public-news__feature"><p className="vh-kicker"><Waves size={15}/> Noticia · Ejemplo</p><h2>Restauración Carolina inicia su prototipo de seguimiento</h2><p>Presentación del prototipo académico.</p><span>25 septiembre 2026 · Contenido demostrativo</span></article><article className="public-news__event"><p className="vh-kicker"><CalendarDays size={15}/> Actividad planificada · Demo</p><h2>Jornada demostrativa de restauración</h2><div><MapPin size={15}/> Isla Tortuga</div><p>04 octubre 2026 · 12 participantes previstos en el dato de ejemplo.</p></article></section></main>; }
function App() { return <Routes><Route element={<PublicLayout/>}><Route path="/" element={<Home/>}/><Route path="/proyecto" element={<Project/>}/><Route path="/mapa" element={<InteractiveMapPage/>}/><Route path="/galeria" element={<InteractiveGallery/>}/><Route path="/noticias" element={<News/>}/><Route path="/login" element={<Login/>}/><Route path="/corales/:id" element={<Coral/>}/></Route><Route element={<PrivateRoute/>}><Route element={<PrivateLayout/>}><Route path="/dashboard" element={<CoreDashboard/>}/><Route path="/observaciones" element={<Observations/>}/></Route></Route></Routes>; }
ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><AuthProvider><App/></AuthProvider></BrowserRouter></React.StrictMode>);
